export const CLEAR_BREADCRUMBS = "CLEAR_BREADCRUMBS";
export const ADD_BREADCRUMB_ITEM = "ADD_BREADCRUMB_ITEM";
export const REPLACE_BREADCRUMB_LAST_ITEM = "REPLACE_BREADCRUMB_LAST_ITEM";

export const SHOW_SPINNER = "SHOW_SPINNER";
export const HIDE_SPINNER = "HIDE_SPINNER";
export const SNACK_MESSAGE = "SNACK_MESSAGE";
export const HIDE_SNACK = "HIDE_SNACK";

export const AXIOS_AUTH_INTERCEPTOR = "AXIOS_AUTH_INTERCEPTOR";

export const LOAD_QUOTE_REQUEST = "LOAD_QUOTE_REQUEST";
export const QUOTE_SUCCESS = "QUOTE_SUCCESS";
export const DELETE_QUOTE_ITEM_REQUEST = "DELETE_QUOTE_ITEM_REQUEST";
export const UPDATE_QUOTE_ITEM_QTY_REQUEST = "UPDATE_QUOTE_ITEM_QTY_REQUEST";
export const QUOTE_ASSIGN_SHIPPING_ADDRESS_REQUEST = "QUOTE_ASSIGN_SHIPPING_ADDRESS_REQUEST";

export const CATALOG_SEARCH_REQUEST = "CATALOG_SEARCH_REQUEST";
export const CATALOG_SEARCH_SUCCESS = "CATALOG_SEARCH_SUCCESS";
export const CATALOG_SEARCH_PAGINATE_TO = "CATALOG_SEARCH_PAGINATE_TO";
export const CATALOG_SEARCH_PAGINATE_PER_PAGE = "CATALOG_SEARCH_PAGINATE_PER_PAGE";
export const CATALOG_SEARCH_SORT_BY = "CATALOG_SEARCH_SORT_BY";

export const BIND_CUSTOMER = "BIND_CUSTOMER";
export const CHECKOUT_AS_GUEST_CUSTOMER = "CHECKOUT_AS_GUEST_CUSTOMER";
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
