export const CLEAR_BREADCRUMBS = "CLEAR_BREADCRUMBS";
export const ADD_BREADCRUMB_ITEM = "ADD_BREADCRUMB_ITEM";
export const REPLACE_BREADCRUMB_LAST_ITEM = "REPLACE_BREADCRUMB_LAST_ITEM";

export const SET_THEME_DATA = "SET_THEME_DATA";

export const SHOW_SPINNER = "SHOW_SPINNER";
export const HIDE_SPINNER = "HIDE_SPINNER";
export const SNACK_MESSAGE = "SNACK_MESSAGE";
export const HIDE_SNACK = "HIDE_SNACK";

export const AXIOS_AUTH_INTERCEPTOR = "AXIOS_AUTH_INTERCEPTOR";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";