export default {
  "theme-toolbar": "components/ThemeToolbar.vue",
  "theme-footer": "components/ThemeFooter.vue",
  "image-card": "components/ImageCard.vue",
  "image-section": "components/ImageSection.vue",
  "image-carsousel": "components/ImageCarousel.vue",
  "image-gallery": "components/ImageGallery.vue",
  "product-simple-card": "components/ProductSimpleCard.vue",
  "product-full-card": "components/ProductFullCard.vue",
  "product-detail": "components/ProductDetail.vue",
  "product-list": "components/ProductList.vue",
  "qty-select": "components/QtySelect.vue",
  "shopping-cart-card": "components/ShoppingCartCard.vue",
  "mini-cart-card": "components/MiniCartCard.vue",
  "checkout-contact-card": "components/Checkout/ContactDetailsCard.vue",
  "checkout-address-card": "components/Checkout/AddressCard.vue",
  "checkout-payment-card": "components/Checkout/PaymentCard.vue",
  "checkout-cart-card": "components/Checkout/CartCard.vue",
  "checkout-main-card": "components/Checkout/MainCard.vue"
}