export default {
    "spinner-layer": "components/SpinnerLayer.vue",
    "theme-toolbar": "components/ThemeToolbar.vue",
    "theme-footer": "components/ThemeFooter.vue",
    "image-card": "components/images/ImageCard.vue",
    "image-carsousel": "components/images/ImageCarousel.vue",
    "image-gallery": "components/images/ImageGallery.vue",
    "product-color-swatch-card": "components/catalog/product/swatch/Color.vue",
    "product-size-swatch-card": "components/catalog/product/swatch/Size.vue",
    "product-swatches-card": "components/catalog/product/swatch/ProductSwatches.vue",

    "mini-simple-product-card": "components/catalog/product/minicard/Simple.vue",
    "mini-general-product-card": "components/catalog/product/minicard/General.vue",
    "mini-variation-product-card": "components/catalog/product/minicard/Variation.vue",
    "full-simple-product-card": "components/catalog/product/fullcard/Simple.vue",
    "full-configurable-product-card": "components/catalog/product/fullcard/Configurable.vue",
    "full-downloadable-product-card": "components/catalog/product/fullcard/Downloadable.vue",
    "mini-cart-item-simple": "components/catalog/product/cartitem/MiniSimple.vue",
    "full-cart-item-simple": "components/catalog/product/cartitem/FullSimple.vue",
    "mini-cart-item-configurable": "components/catalog/product/cartitem/Configurable.vue",

    "product-tab": "components/catalog/product/tab/Tab.vue",
    "product-tabs": "components/catalog/product/tab/Tabs.vue",

    "product-grid": "components/catalog/product/ProductGrid.vue",
    "qty-select": "components/QtySelect.vue",
    "shopping-cart-card": "components/cart/ShoppingCartCard.vue",
    "mini-cart-card": "components/cart/MiniCartCard.vue",
    "checkout-contact-card": "components/checkout/ContactDetailsCard.vue",
    "google-address-autocomplete": "components/MyGoogleAddressAutoComplete.vue",
    "checkout-address-card": "components/checkout/AddressCard.vue",
    "checkout-payment-card": "components/checkout/PaymentCard.vue",
    "checkout-cart-card": "components/checkout/CartCard.vue",
    "checkout-main-card": "components/checkout/MainCard.vue",
    "search-result-card": "components/catalog/search/SearchResultCard.vue",
    "search-result-page": "components/catalog/search/SearchResultRoutePage.vue",
    "filters-card": "components/catalog/search/filter/FiltersCard.vue",
    "price-filter-bullet": "components/catalog/search/filter/PriceFilterBullet.vue",
    "dynamic-attribute-filter-bullet": "components/catalog/search/filter/DynamicAttributeFilterBullet.vue",
    "category-filter-bullet": "components/catalog/search/filter/CategoryFilterBullet.vue",
    "a-pagination": "components/catalog/search/filter/Pagination.vue",
    "sort-control": "components/catalog/search/filter/SortControl.vue",
    // "paypal-card": "components/Checkout/PaymentMethod/PaypalCard.vue"
}