export default {
    "spinner-layer": "components/SpinnerLayer.vue",
    "theme-toolbar": "components/ThemeToolbar.vue",
    "theme-footer": "components/ThemeFooter.vue",
    "image-card": "components/ImageCard.vue",
    "image-carsousel": "components/ImageCarousel.vue",
    "image-gallery": "components/ImageGallery.vue",
    "general-product-card": "components/catalog/product/card/GeneralProductCard.vue",
    "simple-product-card": "components/catalog/product/card/SimpleProductCard.vue",
    "product-full-card": "components/catalog/product/ProductFullCard.vue",
    "product-detail": "components/catalog/product/ProductDetail.vue",
    "product-grid": "components/catalog/product/ProductGrid.vue",
    "qty-select": "components/QtySelect.vue",
    "shopping-cart-card": "components/ShoppingCartCard.vue",
    "mini-cart-card": "components/MiniCartCard.vue",
    "checkout-contact-card": "components/Checkout/ContactDetailsCard.vue",
    "google-address-autocomplete": "components/MyGoogleAddressAutoComplete.vue",
    "checkout-address-card": "components/Checkout/AddressCard.vue",
    "checkout-payment-card": "components/Checkout/PaymentCard.vue",
    "checkout-cart-card": "components/Checkout/CartCard.vue",
    "checkout-main-card": "components/Checkout/MainCard.vue",
    "search-result-card": "components/catalog/search/SearchResultCard.vue",
    "search-result-page": "components/catalog/search/SearchResultRoutePage.vue",
    "filters-card": "components/catalog/search/filter/FiltersCard.vue",
    "price-filter-bullet": "components/catalog/search/filter/PriceFilterBullet.vue",
    "dynamic-attribute-filter-bullet": "components/catalog/search/filter/DynamicAttributeFilterBullet.vue",
    "category-filter-bullet": "components/catalog/search/filter/CategoryFilterBullet.vue",
    "a-pagination": "components/catalog/search/filter/Pagination.vue",
    "sort-control": "components/catalog/search/filter/SortControl.vue",
    // "paypal-card": "components/Checkout/PaymentMethod/PaypalCard.vue"
}